version: 0.2

env:
  shell: "bash"
  git-credential-helper: yes
  secrets-manager:
    DOCKER_ACCESS_KEY: "build:dockerhub_accesskey"
    DOCKER_USER: "build:dockerhub_username"
    GITHUB_PACKAGE_READ_KEY: "build:github_package_read_key"

phases:
  install:
    runtime-versions:
      docker: 20

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo $COMMIT_HASH
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo $IMAGE_TAG
  build:
    commands:
      - echo Build started on `date`
      - echo $DOCKER_ACCESS_KEY | docker login --username $DOCKER_USER --password-stdin
      - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$ENVIRONMENT || true
      - docker build --build-arg GITHUB_PACKAGE_READ_KEY=$GITHUB_PACKAGE_READ_KEY -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$ENVIRONMENT
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$ENVIRONMENT
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - 'echo "[{\"name\":\"$APP_NAME\", \"imageUri\": \"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$ENVIRONMENT\"}]" > imagedefinitions.json'

artifacts:
  files:
    - imagedefinitions.json
